num1 = int(input("Give a number: "))
num2 = int(input("Give another number: "))
print(f"The sum is {num1 + num2}")
print(f"The difference is {num1 - num2}")
print(f"The product is {num1 * num2}")
print(f"The quotient is {num1 / num2}")